version: '3'

networks:
  app-tier:
    driver: bridge

services:
  task-etcd:
    depends_on:
      - etcd 
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /
    ports:
      - 8080:8080
    environment:
        HOST_NAME: "localhost"
        LISTEN_PORT: 8080 
        LOG_LEVEL: "debug"
        ETCD_URLS: etcd:2379

        GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
        GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
        GITHUB_TIMEOUT_IN_SEC: 2
        GITHUB_OAUTH_URL: "https://github.com/login/oauth"
        GITHUB_API_URL: "https://api.github.com"

        JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
        # JWT expiry duration is 2 days
        JWT_EXPIRY_IN_MINS: 2880

    networks:
      - app-tier
  
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier
